name: TonyWild
favicon: null
layout_spectrum: 0.31194659625180066
typography_spectrum: 0.05237980652600527
title: TonyWild
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed7d0'
    - '#9d8ea3'
    - '#322030'
    - '#7b6886'
    - '#c76c71'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
